{
 "title": "AlphaGameBot Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "AlphaGameBot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{service_name=\"AlphaGameBot\"} | json | line_format \"{{.level}}: {{.message}}\""
    }
   ]
  },
  {
   "title": "Metrics Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alphagamebot_metrics_generation_time_ms",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Metrics Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "alphagamebot_metrics_queue_length",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Event Execution Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alphagamebot_event_executed_duration_ms",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "alphagamebot_nodejs_eventloop_lag_seconds",
     "legendFormat": "Current Lag"
    },
    {
     "expr": "alphagamebot_nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "Mean Lag"
    },
    {
     "expr": "alphagamebot_nodejs_eventloop_lag_max_seconds",
     "legendFormat": "Max Lag"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(alphagamebot_process_cpu_user_seconds_total[1m])",
     "legendFormat": "User CPU"
    },
    {
     "expr": "rate(alphagamebot_process_cpu_system_seconds_total[1m])",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "Active Handles & Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "alphagamebot_nodejs_active_handles_total",
     "legendFormat": "Handles Total"
    },
    {
     "expr": "alphagamebot_nodejs_active_requests_total",
     "legendFormat": "Requests Total"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alphagamebot_nodejs_heap_size_used_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "alphagamebot_nodejs_heap_size_total_bytes",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GC Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(alphagamebot_nodejs_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Memory & File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alphagamebot_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "alphagamebot_process_virtual_memory_bytes",
     "legendFormat": "Virtual Memory"
    },
    { "expr": "alphagamebot_process_open_fds", "legendFormat": "Open FDs" },
    { "expr": "alphagamebot_process_max_fds", "legendFormat": "Max FDs" }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    { "title": "Total Connections", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 56 } },
    {
     "title": "Max Used Connections (Time)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_max_used_connections_time",
       "legendFormat": "Max Connection Time"
      }
     ]
    },
    {
     "title": "Buffer Pool Dirty Pages",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 8, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_buffer_pool_dirty_pages",
       "legendFormat": "Dirty Pages"
      }
     ]
    },
    {
     "title": "Performance Schema Connect Attr Longest Seen",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_performance_schema_lost_total{instrumentation=\"session_connect_attrs_longest_seen\"}",
       "legendFormat": "Attr Length"
      }
     ]
    },
    {
     "title": "Buffer Pool Pages by State",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_buffer_pool_pages",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Collector Duration (seconds)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_exporter_collector_duration_seconds",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "Collector Success State",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "mysql_exporter_collector_success",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "Aborted Clients / Connects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "mysql_global_status_aborted_clients",
       "legendFormat": "Aborted Clients"
      },
      {
       "expr": "mysql_global_status_aborted_connects",
       "legendFormat": "Aborted Connects"
      }
     ]
    },
    {
     "title": "Network Traffic (Bytes Sent / Received)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "mysql_global_status_bytes_sent", "legendFormat": "Bytes Sent" },
      {
       "expr": "mysql_global_status_bytes_received",
       "legendFormat": "Bytes Received"
      }
     ]
    },
    {
     "title": "Commands Executed (Selected Commands)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_commands_total{command=~\"select|insert|commit|create_table|show_keys|show_create_table|show_replica_status\"}[$__rate_interval])",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "MySQL Commands Executed",
     "type": "piechart",
     "gridPos": { "h": 24, "w": 6, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_commands_total>0",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Opened Objects (Tables, Files, Definitions)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 94 },
     "targets": [
      {
       "expr": "mysql_global_status_opened_tables",
       "legendFormat": "Opened Tables"
      },
      {
       "expr": "mysql_global_status_opened_table_definitions",
       "legendFormat": "Opened Table Definitions"
      },
      {
       "expr": "mysql_global_status_opened_files",
       "legendFormat": "Opened Files"
      }
     ]
    },
    {
     "title": "Open Tables & Files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 94 },
     "targets": [
      {
       "expr": "mysql_global_status_open_tables",
       "legendFormat": "Open Tables"
      },
      { "expr": "mysql_global_status_open_files", "legendFormat": "Open Files" },
      {
       "expr": "mysql_global_status_open_table_definitions",
       "legendFormat": "Open Table Definitions"
      }
     ]
    },
    {
     "title": "Performance Schema Lost Metrics",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 6, "y": 102 },
     "targets": [
      {
       "expr": "mysql_global_status_performance_schema_lost_total>0",
       "legendFormat": "{{instrumentation}}"
      }
     ]
    },
    {
     "title": "MySQLX SSL and Worker Info",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 102 },
     "targets": [
      {
       "expr": "mysql_global_status_mysqlx_ssl_ctx_verify_depth",
       "legendFormat": "SSL Verify Depth"
      },
      {
       "expr": "mysql_global_status_mysqlx_ssl_ctx_verify_mode",
       "legendFormat": "SSL Verify Mode"
      },
      {
       "expr": "mysql_global_status_mysqlx_worker_threads",
       "legendFormat": "Worker Threads"
      },
      {
       "expr": "mysql_global_status_mysqlx_worker_threads_active",
       "legendFormat": "Active Threads"
      }
     ]
    },
    {
     "title": "InnoDB Row Operations",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 6, "y": 115 },
     "targets": [
      {
       "expr": "mysql_global_status_innodb_row_ops_total",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Usage",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_data / mysql_global_status_innodb_redo_log_capacity_resized * 100",
       "legendFormat": "Usage %"
      }
     ]
    },
    {
     "title": "InnoDB Read vs Write Operations",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_innodb_data_reads",
       "legendFormat": "Reads"
      },
      {
       "expr": "mysql_global_status_innodb_data_writes",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Temporary Objects Created",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 6, "y": 128 },
     "targets": [
      { "expr": "created_tmp_tables", "legendFormat": "Temp Tables" },
      {
       "expr": "mysql_global_status_created_tmp_files",
       "legendFormat": "Temp Files"
      },
      {
       "expr": "mysql_global_status_created_tmp_disk_tables",
       "legendFormat": "Temp Disk Tables"
      }
     ]
    },
    {
     "title": "Handler Operations (Top Types)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 128 },
     "targets": [
      {
       "expr": "rate(mysql_global_status_handlers_total[$__rate_interval])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  }
 ]
}